### ISSUE TITLE
isssue

### ISSUE THREAD

**Issue by banline** [Tbot223/server_client#1]
중대한 결함이 발견되어 알려드립니다.

```
name: "Greet With A Random Meme"
on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    name: setup environment
    runs-on: ubuntu-latest
    steps:
      - name: memes on isssues
        uses: deep5050/memes-on-issues-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
